In [1]:
import numpy as np
array1=  np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist()) #tolist() list 자료형으로 변환시키기

#3차원을 2차원으로
array5 = array3d.reshape(-1, 1)
print('array5 shape:\n', array5.shape)

#1차원을 2차원으로
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5 shape:
 (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [3]:
#단일 값 추출 []
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
value = array1[2]
print('value:', value)
print(type(value))

print('맨 뒤에서 두번 째 값:', array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤에서 두번 째 값: 8


In [5]:
#인덱스 수정 =
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [6]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [8]:
array1 = np.arange(1, 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
array1 = np.arange(1, 10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [11]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 1:3] \n', array2d[1:3, 1:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:2, 0] \n', array2d[:2, 0])

print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)


array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 1:3] 
 [[5 6]
 [8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:2, 0] 
 [1 4]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [13]:
#Fancy indexing
#리스트나 ndarray로 인덱스 집찹을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0,1], 2]
print('array3d[[0,1], 2] =>', array3.tolist())

array4 = array2d[[0,2], 0:2]
print('array2d[[0, 2], 0:2]=>', array4.tolist())


array3d[[0,1], 2] => [3, 6]
array2d[[0, 2], 0:2]=> [[1, 2], [7, 8]]


In [14]:
#Boolean indexing

array1d = np.arange(1, 10)
# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3 )


array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [15]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [16]:
boolean_index = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_index]
print('불린 인덱스로 필터링 결과 :', array3)


불린 인덱스로 필터링 결과 : [6 7 8 9]


In [17]:
indexs = np.array([5, 6, 7, 8])
array4 = array1d[indexs]
print('일반 인덱스로 필터링 결과:', array4)

#boolean index에서 True값에 해당하는 index 저장 -> 저장된 index값으로 데이터 조회

일반 인덱스로 필터링 결과: [6 7 8 9]


In [18]:
#np.sort()와 ndarray.sort()
org_array = np.array([3, 1, 9, 5])
print('원본행렬:', org_array)

sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반횐된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)


원본행렬: [3 1 9 5]
np.sort() 호출 후 반횐된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]


In [19]:
#[::-1]
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순 정렬 :', sort_array1_desc)

array2d = np.array([[8, 12],
                    [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

내림차순 정렬 : [9 5 3 1]
로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [21]:
#np.argsort() 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(np.sort(org_array))
print(type(sort_indices))
print('행렬 정렬시 원본 행렬의 인덱스:', sort_indices)

[1 3 5 9]
<class 'numpy.ndarray'>
행렬 정렬시 원본 행렬의 인덱스: [1 0 3 2]


In [22]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [23]:
#argsort() 활용
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indicies_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indicies_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indicies_asc]) #name_array에 팬시 인덕스로 적용해 추출


성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [24]:
#행렬 내적(행렬 곱)
#np.dot(A, B)
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [25]:
#전치 행렬: 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
#np.transpose()
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치행렬:\n', transpose_mat)

A의 전치행렬:
 [[1 3]
 [2 4]]
